services:
  db:
    image: mysql:8.0
    container_name: mysql_safeboleto
    restart: always
    environment:
      MYSQL_DATABASE: safeboleto_db
      MYSQL_USER: user
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3307:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "user", "--password=${MYSQL_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: app_safeboleto
    ports:
      - "8080:8080"
    environment:
      # O Spring usará estas variáveis para se conectar ao banco de dados.
      # O nome 'db' é o nome do serviço do banco de dados definido acima.
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/safeboleto_db?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update # Garante que as tabelas sejam criadas/atualizadas ao iniciar
    depends_on:
      db:
        condition: service_healthy