services:
  db:
    image: postgres:17-alpine
    container_name: postgres_safeboleto
    environment:
      POSTGRES_DB: safeboleto_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Lukinhas12
    ports:
      - "5432:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: app_safeboleto
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      # --- Conex√£o com PostgreSQL 17 em Docker ---
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/safeboleto_db?connectTimeout=10&socketTimeout=30
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Lukinhas12
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "false"
      SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE: 5
      SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT: 30000
      SPRING_DATASOURCE_HIKARI_IDLE_TIMEOUT: 600000
      SPRING_DATASOURCE_HIKARI_MAX_LIFETIME: 1800000

volumes:
  postgres_volume: